server:
  port: 81
  
spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://49.235.59.157:9411
    sleuth:
      sampler:
        probability: 1

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance:
    instance-id: consumer81
    prefer-ip-address: true



